### ISSUE TITLE
Evaluation metrics: ABO and mAP

### ISSUE THREAD

**Issue by IssamLaradji** [ZhouYanzhao/PRM#4]
Thanks for the code!

What scripts did you use to compute the mAP and the average best overlapping (ABO) metrics?

Thanks!

**Comment by ZhouYanzhao** [comment]
Hi @IssamLaradji ,
Please refer to the [PASCAL VOC dataset](http://host.robots.ox.ac.uk/pascal/VOC/voc2012/) for metric definition.

**Comment by IssamLaradji** [comment]
Makes sense, thanks. :)

**Comment by GuoleiSun** [comment]
mAP is easy.
But what scripts do you use to calculate ABO? I use this code to calculate ABO, but get different number compared to your paper. The link is here: https://github.com/sergeyk/selective_search_ijcv_with_python/blob/master/BoxAverageBestOverlap.m
Of course, I change to code to calculate IOU between masks, rather than using box.
